put build in compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -337,6 +337,18 @@ fi
 mmeasure 'python.size' "$(measure-size)"
 
 
+for file in "$ENV_DIR"/*
+do
+  [[ -f "$file" ]] || continue
+  var="${file##*/}"
+  if
+    printf -v "$var" "$(<"$file")" 2>/dev/null
+  then
+    export "$var"
+  else
+    echo "Invalid filename: $file"
+  fi
+done
 
 cd $BUILD_DIR
 /app/.heroku/python/bin/python heroku_buildpack.py
