added post_compile script

diff --git a/bin/post_compile b/bin/post_compile
--- a/bin/post_compile
+++ b/bin/post_compile
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+echo "ERROR!"
+exit 127
 
 
 BUILD_DIR=$1
