added printenv

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -6,6 +6,27 @@ set -euo pipefail
 BUILD_DIR=$1
 BUILDPACK_DIR=$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" && pwd)
 
+
+printenv
+
+for file in "$ENV_DIR"/*
+do
+  [[ -f "$file" ]] || continue
+  var="${file##*/}"
+  if
+    printf -v "$var" "$(<"$file")" 2>/dev/null
+  then
+    export "$var"
+  else
+    echo "Invalid filename: $file"
+  fi
+done
+
+cd $BUILD_DIR
+/app/.heroku/python/bin/python heroku_buildpack.py
+
+
+
 # Unfortunately the build system doesn't source the `export` script before
 # running `bin/release`, so we have to do so manually to ensure the buildpack
 # Python is used by `is_module_available` instead of system Python.
@@ -26,21 +47,3 @@ addons:
   - heroku-postgresql
 EOF
 fi
-
-printenv
-
-for file in "$ENV_DIR"/*
-do
-  [[ -f "$file" ]] || continue
-  var="${file##*/}"
-  if
-    printf -v "$var" "$(<"$file")" 2>/dev/null
-  then
-    export "$var"
-  else
-    echo "Invalid filename: $file"
-  fi
-done
-
-cd $BUILD_DIR
-/app/.heroku/python/bin/python heroku_buildpack.py
