added python run_script

diff --git a/bin/steps/hooks/post_compile b/bin/steps/hooks/post_compile
--- a/bin/steps/hooks/post_compile
+++ b/bin/steps/hooks/post_compile
@@ -7,9 +7,21 @@ if [ -f bin/post_compile ]; then
 fi
 
 
+#!/bin/bash
+dir="."
+for file in "$ENV_DIR"/*
+do
+  [[ -f "$file" ]] || continue
+  var="${file##*/}"
+  if
+    printf -v "$var" "$(<"$file")" 2>/dev/null
+  then
+    export "$var"
+  else
+    echo "Invalid filename: $file"
+  fi
+done
 
-ls $ENV_DIR
 
-cat $ENV_DIR/*
 cd $BUILD_DIR
 /app/.heroku/python/bin/python heroku_buildpack.py
